import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "./components/navbar";
import "xterm/css/xterm.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Network Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <header>
          <Topbar />
        </header>
        {children}
      </body>
    </html>
  );
}



