# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 37221

# Run the application
CMD ["node", "speedtest.js"]